name: Build and Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
          
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install optimizers
      run: |
        npm install -g purgecss
        npm install -g clean-css-cli
        npm install -g html-minifier

    - name: Purge CSS
      run: |
        purgecss \
          --css public/main.css \
          --content public/index.html \
          --output public/purged.css \
          --safelist "grid" "container" "white-background" "parallax-section" "parallax-1" "parallax-2" \
          --font-face \
          --keyframes
    
    - name: Minify CSS
      run: cleancss -o public/main.css public/purged.css
    
    - name: Minify HTML
      run: |
        html-minifier \
          --collapse-whitespace \
          --minify-css \
          --minify-js \
          --minify-urls \
          --remove-comments \
          --remove-empty-attributes \
          --remove-redundant-attributes \
          --remove-script-type-attributes \
          --remove-style-link-type-attributes \
          --use-short-doctype \
          --conservative-collapse \
          --preserve-line-breaks
          public/index.html \
          --o public/index.html \
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
          path: './public'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
